"use client";

import { useState, useCallback } from "react";
import CustomCursor from "../components/CustomCursor";
import DashboardNavbar from "../components/DashboardNavbar";
import Hero from "../components/Hero";
import QueryInput, { CatalogPick } from "../components/QueryInput";
import MultiStepLoader from "../components/MultiStepLoader";
import DashboardSkeleton from "../components/DashboardSkeleton";
import AgentTerminal, { TerminalLog } from "../components/AgentTerminal";
import PriceTable, { PriceRecord } from "../components/PriceTable";
import StatsCards from "../components/StatsCards";
import ApprovalModal from "../components/ApprovalModal";
import DispatchToast from "../components/DispatchToast";
import MarketMap from "../components/MarketMap";
import { FluidParticlesBackground } from "@/components/ui/fluid-particles-background";
import { ShieldCheck } from "lucide-react";

const API_BASE =
  process.env.NEXT_PUBLIC_API_URL || "https://krishidrishti-ai-jtp6.onrender.com";

interface Recommendation {
  best_mandi: string;
  net_margin_per_quintal: number;
  reasoning_summary: string;
  alert_bengali: string;
  alert_english: string;
  requires_approval: boolean;
  confidence: string;
}

interface QueryResult {
  run_id: string;
  query: { crop: string; district: string; state: string };
  price_records: PriceRecord[];
  recommendation: Recommendation;
  status: string;
  data_mode?: "live" | "demo";
}

interface DispatchInfo {
  channel: string;
  recipient_group: string;
  dispatched_at: string;
  delivery_status: string;
  channels: { email: string };
}

export default function DashboardPage() {
  const [logs, setLogs] = useState<TerminalLog[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const [result, setResult] = useState<QueryResult | null>(null);
  const [currentCrop, setCurrentCrop] = useState("Paddy");
  const [currentDistrict, setCurrentDistrict] = useState("");

  const [showModal, setShowModal] = useState(false);
  const [isApproving, setIsApproving] = useState(false);

  const [showToast, setShowToast] = useState(false);
  const [dispatchInfo, setDispatchInfo] = useState<DispatchInfo | null>(null);

  const handleQuery = useCallback(async (pick: CatalogPick) => {
    setIsRunning(true);
    setLogs([]);
    setResult(null);
    setCurrentCrop(pick.crop);
    setCurrentDistrict(pick.district);
    setShowToast(false);

    try {
      const response = await fetch(`${API_BASE}/api/query/stream`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          crop: pick.crop,
          district: pick.district,
          state: pick.state,
          mode: "live",
          commodity_id: pick.commodity_id,
          district_id: pick.district_id,
          state_id: pick.state_id,
          market_id: pick.market_id,
          market_name: pick.market_name,
        }),
      });

      if (!response.ok) throw new Error("Failed to start agent");

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();

      if (!reader) throw new Error("No response body");

      let buffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() || "";

        for (const line of lines) {
          if (line.startsWith("data: ")) {
            try {
              const data = JSON.parse(line.slice(6));

              if (data.type === "result") {
                setResult(data.payload);
                setShowModal(true);
              } else {
                setLogs((prev) => [...prev, data as TerminalLog]);
              }
            } catch {
              // Skip malformed JSON
            }
          }
        }
      }
    } catch (error) {
      setLogs((prev) => [
        ...prev,
        {
          type: "error" as const,
          msg: `[Error] ${error instanceof Error ? error.message : "Connection failed"}. Is the backend running on ${API_BASE}?`,
        },
      ]);
    } finally {
      setIsRunning(false);
    }
  }, []);

  const handleApprove = useCallback(async (messageText: string) => {
    if (!result) return;
    setIsApproving(true);

    try {
      if (!result.run_id) {
        throw new Error("No run_id on this result. Run Fetch again before approving.");
      }

      // 1. Direct client-side Web3Forms API dispatch (bypasses server-side blocks)
      const payload = {
        access_key: "cf6839d1-354d-447d-8623-d64eebbcbb26",
        email: "sayimmullick2005@gmail.com",
        subject: "KrishiDrishti AI: Price & Transport Recommendation",
        message:
          messageText ||
          result.recommendation?.alert_english ||
          result.recommendation?.reasoning_summary ||
          "High price alert generated by KrishiDrishti AI.",
      };

      const w3Response = await fetch("https://api.web3forms.com/submit", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify(payload),
      });

      const w3Data = await w3Response.json().catch(() => ({}));
      if (!w3Response.ok || w3Data.success === false) {
        const errorMsg =
          typeof w3Data.message === "string"
            ? w3Data.message
            : `Web3Forms failed with HTTP ${w3Response.status}`;
        throw new Error(errorMsg);
      }

      // 2. Notify backend to persist approval state
      try {
        await fetch(`${API_BASE}/api/approve`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            run_id: result.run_id,
            approved: true,
            approved_by: "organizer",
            recipients: ["sayimmullick2005@gmail.com", "prototracedev@gmail.com"],
          }),
        });
      } catch {
        // Backend record update is optional
      }

      setDispatchInfo({
        channel: "Web3Forms Email",
        recipient_group: "Transmitted to Official Registry (prototracedev@gmail.com) from Officer (sayimmullick2005@gmail.com)",
        dispatched_at: new Date().toISOString(),
        delivery_status: "sent",
        channels: { email: "sent" },
      });
      setShowModal(false);
      setShowToast(true);

      setLogs((prev) => [
        ...prev,
        {
          type: "success",
          msg: `[KrishiDrishti] ✓ Approved. Transmitted to Official Registry (prototracedev@gmail.com) from Officer (sayimmullick2005@gmail.com) via Web3Forms.`,
        },
      ]);
    } catch (error) {
      setLogs((prev) => [
        ...prev,
        {
          type: "error",
          msg: `[Error] Approval failed: ${error instanceof Error ? error.message : "Unknown error"}`,
        },
      ]);
    } finally {
      setIsApproving(false);
    }
  }, [result]);

  const handleReject = useCallback(async () => {
    if (!result) return;

    try {
      await fetch(`${API_BASE}/api/approve`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          run_id: result.run_id,
          approved: false,
        }),
      });
    } catch {
      // Silent rejection
    }

    setShowModal(false);
    setLogs((prev) => [
      ...prev,
      { type: "error", msg: "[KrishiDrishti] ✗ Alert rejected by organizer. No message dispatched." },
    ]);
  }, [result]);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 relative overflow-x-hidden">
      <CustomCursor />

      {/* Atmospheric Fluid Particles Background */}
      <FluidParticlesBackground className="fixed inset-0 pointer-events-none z-0 min-h-screen" particleCount={900} />

      {/* Solid Executive Ambient Radial Glows */}
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(ellipse_80%_60%_at_50%_-10%,rgba(16,185,129,0.14),transparent_70%)] z-0" />
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(ellipse_60%_50%_at_90%_80%,rgba(34,211,238,0.06),transparent_60%)] z-0" />

      {/* Sleek Collapsible Hamburger Navbar */}
      <DashboardNavbar dataMode={result?.data_mode} isRunning={isRunning} />

      <main className="relative z-10 min-h-screen">
        <Hero />
        
        {/* Unified Search Command Bar */}
        <QueryInput onSubmit={handleQuery} isLoading={isRunning} />

        {/* Multi-Step Execution Pipeline Indicator */}
        <MultiStepLoader
          isLoading={isRunning}
          crop={currentCrop}
          district={currentDistrict}
        />

        {result?.data_mode && (
          <div className="max-w-7xl mx-auto px-4 sm:px-6 mb-3">
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-slate-900/90 border border-emerald-500/30 backdrop-blur-xl text-xs font-mono shadow-md">
              <span className={`h-2 w-2 rounded-full ${result.data_mode === "live" ? "bg-emerald-400 animate-pulse" : "bg-amber-400"}`} />
              <span className={result.data_mode === "live" ? "text-emerald-300 font-bold" : "text-amber-300 font-bold"}>
                {result.data_mode === "live" ? "AGMARKNET LIVE DATA STREAM" : "DEMO DATA ARCHIVE"}
              </span>
            </div>
          </div>
        )}

        <div className="max-w-7xl mx-auto px-4 sm:px-6 pb-12">
          
          {/* Step 0: Initial Idle State (Awaiting Query) */}
          {!logs.length && !isRunning && !result && (
            <div className="max-w-2xl mx-auto mt-8 p-8 rounded-2xl bg-gradient-to-br from-slate-950/80 via-slate-900/60 to-emerald-950/20 backdrop-blur-xl border border-emerald-500/25 text-center shadow-2xl">
              <div className="w-12 h-12 rounded-2xl bg-emerald-500/15 border border-emerald-500/30 text-emerald-400 flex items-center justify-center mx-auto mb-4">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold text-white mb-1.5">
                Awaiting Officer Query Initiation
              </h3>
              <p className="text-xs text-slate-300 max-w-md mx-auto leading-relaxed">
                Select a target commodity and home district in the command bar above, then click <strong className="text-emerald-400 font-semibold">Fetch Prices</strong> to launch real-time Agmarknet data ingestion and logistics calculations.
              </p>
            </div>
          )}

          {/* Step 1 & 2: Search Triggered & Computing (Progressive Reveal) */}
          {isRunning && !result && (
            <div className="space-y-5 animate-fade-in">
              <DashboardSkeleton crop={currentCrop} district={currentDistrict} />
              
              <div className="grid grid-cols-1 lg:grid-cols-5 gap-4 items-start">
                <div className="lg:col-span-2 min-h-[440px]">
                  <AgentTerminal logs={logs} isRunning={isRunning} />
                </div>
                <div className="lg:col-span-3">
                  <PriceTable records={[]} bestMandi="" />
                </div>
              </div>
            </div>
          )}

          {/* Step 3: Final State (Full Results & Map Unlocked) */}
          {result && (
            <div className="space-y-5 animate-fade-in">
              {/* Executive Stats Cards */}
              <StatsCards
                recommendation={result.recommendation || null}
                totalMandis={result.price_records.length || 0}
                crop={currentCrop}
                district={result.query?.district || currentDistrict}
              />

              {/* Main Intelligence Grid */}
              <div className="grid grid-cols-1 lg:grid-cols-5 gap-4 items-start">
                <div className="lg:col-span-2 min-h-[480px]">
                  <AgentTerminal logs={logs} isRunning={isRunning} />
                </div>

                <div className="lg:col-span-3 space-y-4">
                  <PriceTable
                    records={result.price_records || []}
                    bestMandi={result.recommendation?.best_mandi || ""}
                  />
                  <MarketMap
                    records={result.price_records || []}
                    bestMandi={result.recommendation?.best_mandi || ""}
                  />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Executive Footer */}
        <footer className="border-t border-emerald-500/15 bg-slate-950/85 backdrop-blur-xl py-6 mt-16">
          <div className="max-w-7xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="flex items-center gap-2 text-xs text-slate-300">
              <span className="gradient-text font-black text-sm">KrishiDrishti AI</span>
              <span>·</span>
              <span>GovTech Agricultural Intelligence Platform</span>
            </div>
            <div className="flex items-center gap-4 text-xs text-slate-300">
              <span className="flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                Authorized Dispatch Security
              </span>
              <span>·</span>
              <span>Open Source Public GovTech Initiative</span>
            </div>
          </div>
        </footer>
      </main>

      <ApprovalModal
        isOpen={showModal}
        recommendation={result?.recommendation || null}
        onApprove={handleApprove}
        onReject={handleReject}
        isApproving={isApproving}
        region={result?.query?.district}
      />

      <DispatchToast
        isVisible={showToast}
        dispatch={dispatchInfo}
        onClose={() => setShowToast(false)}
      />
    </div>
  );
}


